
try{
allert("test");
}catch (error){
    console.log(error.message)
}